### PR TITLE
Add missing cheerio dev dependency

### PR DESCRIPTION
**Pull request by jonthenerd**
See issue #42 .

### CODE REVIEW

**Comment by coryhouse** [comment]
Thanks for the PR, but this shouldn't be necessary because cheerio is Enzyme's dependency. If you look in node_modules you should find that cheerio is installed. I've confirmed it works fine for me, and it's odd that you're the first to report after so many users. What OS, node version, and command line are you using so I can try to reproduce this issue?

**Comment by jonthenerd** [comment]
## Config details from the issue details

**Node version:** 4.6.0

**npm version:** 2.15.9

**Operating system:**
macOS Sierra

**Command line used:**
npm run build

**Steps to reproduce:**

- Follow Pluralsight course
- Skip Testing modules
- Get to "Review Results" and do a "npm run build"
- Observe that cheerio isn't present to build html.

## Additional Details
I attempted to reproduce this morning, and was able to. Here's my steps for reproducing:

- Reversed my commit on the cloned forked repo, bringing it in line with yours.
- Ran `npm install` . Observed that node_modules folder is created and does not contain a cheerio folder directly. Observed that enzyme folder does exist and has a node_module dependency within it  named cheerio.
- Copied in my src folder, tools folder, and webpack.config.prod.js
- Ran `npm run build` . Build failed with lint error:
`/Users/jon/DEV/pluralsight-redux-starter/tools/buildHtml.js (1/0)
 2:21  Unable to resolve path to module 'cheerio'  import/no-unresolved`
- Looked at referenced line number in buildHtml.js:
`import cheerio from 'cheerio';`

## Thoughts
It's clear that my build isn't resolving the path to cheerio, though I'm not certain why yet. I'm not familiar enough with npm / webpack / es6-lint. I'll look into it a bit more this morning. If you're saying that cheerio should be listed as a direct dependency under node_modules, well it's not on mine (but is listed as a dependency of the direct dependency enzyme). Time to get Googling...

**Comment by jonthenerd** [comment]
For good measure, I removed the lint step in the rebuild step of package.json. Build still failed with error `Error: Cannot find module 'cheerio'` when running `babel-node tools/buildHtml.js` (the build:html step).

From what little I've found online, sub node_modules of directly referenced node_modules cannot be included in import statements with webpack, at least not by their short name (e.g. `import cheerio form 'cheerio';`). 

Question - does your list of node_modules directly in the repo directory contain cheerio? Right after the bootstrap module?

I don't mean to waste your time trying to figure out a config issue on my end. More than anything, your tutorial was great and I hit this last little snag and thought I'd help the next guy out.

**Comment by coryhouse** [comment]
No need to apologize. I really appreciate you bringing this to my attention. 

Yes, cheerio is installed in my node_modules at the root: https://www.dropbox.com/s/hq5soxbm4h5sclo/Screenshot%202016-12-21%2009.35.08.png?dl=0

I believe the core difference is you're running npm 2. **In npm 3, dependencies are flattened so all the deps are installed at the root**. That's why you see so many more folders in my screenshot than I suspect you have in your node_modules root.

So all that said, you're right, I need to add cheerio to package.json to support those using npm 2. Thanks for bringing this to my attention! 💯

**Comment by jonthenerd** [comment]
That's good to know about npm 3. Will be interesting to see if that complicates builds w/large numbers of node modules. Thanks again!

**Pull request merged**
